#!/usr/bin/env bash
# Idempotent bootstrap for the Guidemate Cloud Agent environment.
# Installs workspace dependencies and writes local dev env files using only
# public/safe values. Real secrets (service-role key, backend signer key,
# Gemini/LiveKit/Kotani keys) are intentionally left blank so they can be
# supplied as Cloud Agent secrets without being committed.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "[setup] Installing workspace dependencies (npm ci)..."
npm ci

# --- Public, browser-safe values already published in render.yaml / ci.yml ---
PUBLIC_SUPABASE_URL="https://oeyynnedpmuhfqxkecyt.supabase.co"
PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9leXlubmVkcG11aGZxeGtlY3l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc5NDg3NTQsImV4cCI6MjEwMzUyNDc1NH0.RV0GAn_EEMn5Gyh5HlqnJOR8JmEc-ltzNAkLjGdS7_g"
PUBLIC_FUJI_RPC_URL="https://api.avax-test.network/ext/bc/C/rpc"
PUBLIC_MOCK_USDC_ADDRESS="0x76EC76a347115afa9a3490a256bA13447cfBd8c5"
PUBLIC_ESCROW_ADDRESS="0x4837EfB8422143fdaa4f60805fC05a21cc9966C0"

# Prefer real secrets from the environment when present (Cloud Agent secrets),
# otherwise fall back to safe local dev defaults.
DEV_WALLET_ENCRYPTION_KEY="${WALLET_ENCRYPTION_KEY:-$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")}"
DEV_QR_SIGNING_SECRET="${QR_SIGNING_SECRET:-guidemate_local_dev_qr_secret}"
# The Supabase JS client throws at import if the key is empty, which would stop
# the backend from booting at all. Fall back to a clearly-labeled placeholder so
# the server starts (health/FX and the frontend UI work); Supabase-backed routes
# activate once a real SUPABASE_SERVICE_ROLE_KEY secret is provided.
DEV_SUPABASE_SERVICE_ROLE_KEY="${SUPABASE_SERVICE_ROLE_KEY:-placeholder-service-role-key-set-a-real-secret-to-enable-db}"

write_backend_env() {
  local target="backend/.env"
  if [ -f "$target" ]; then
    echo "[setup] $target already exists, leaving it untouched."
    return
  fi
  echo "[setup] Writing $target"
  cat > "$target" <<EOF
# Auto-generated by .cursor/setup-dev-env.sh for local Cloud Agent development.
# Public testnet/demo values only. Fill in the blank secrets to enable the
# Supabase-backed and on-chain flows (service-role key, backend signer, etc.).
FUJI_RPC_URL=${FUJI_RPC_URL:-$PUBLIC_FUJI_RPC_URL}
BACKEND_PRIVATE_KEY=${BACKEND_PRIVATE_KEY:-}
ESCROW_ADDRESS=${ESCROW_ADDRESS:-$PUBLIC_ESCROW_ADDRESS}
MOCK_USDC_ADDRESS=${MOCK_USDC_ADDRESS:-$PUBLIC_MOCK_USDC_ADDRESS}
PROTOCOL_TREASURY_ADDRESS=${PROTOCOL_TREASURY_ADDRESS:-}

SUPABASE_URL=${SUPABASE_URL:-$PUBLIC_SUPABASE_URL}
SUPABASE_SERVICE_ROLE_KEY=${DEV_SUPABASE_SERVICE_ROLE_KEY}

GEMINI_API_KEY=${GEMINI_API_KEY:-}
GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-flash}

QR_SIGNING_SECRET=${DEV_QR_SIGNING_SECRET}
WALLET_ENCRYPTION_KEY=${DEV_WALLET_ENCRYPTION_KEY}

USDC_TO_KES_RATE=${USDC_TO_KES_RATE:-145}
PORT=${PORT:-4000}
RAMP_PROVIDER=${RAMP_PROVIDER:-simulate}
CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}

LIVEKIT_API_KEY=${LIVEKIT_API_KEY:-}
LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET:-}
LIVEKIT_URL=${LIVEKIT_URL:-}
EOF
}

write_frontend_env() {
  local target="frontend/.env.local"
  if [ -f "$target" ]; then
    echo "[setup] $target already exists, leaving it untouched."
    return
  fi
  echo "[setup] Writing $target"
  cat > "$target" <<EOF
# Auto-generated by .cursor/setup-dev-env.sh for local Cloud Agent development.
# All NEXT_PUBLIC_* values are browser-safe and already published in render.yaml.
NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://localhost:4000}
NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL:-$PUBLIC_SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY:-$PUBLIC_SUPABASE_ANON_KEY}
NEXT_PUBLIC_MOCK_USDC_ADDRESS=${NEXT_PUBLIC_MOCK_USDC_ADDRESS:-$PUBLIC_MOCK_USDC_ADDRESS}
NEXT_PUBLIC_FUJI_RPC_URL=${NEXT_PUBLIC_FUJI_RPC_URL:-$PUBLIC_FUJI_RPC_URL}
NEXT_PUBLIC_LIVEKIT_URL=${NEXT_PUBLIC_LIVEKIT_URL:-}
EOF
}

write_backend_env
write_frontend_env

echo "[setup] Done."
